### ISSUE TITLE
ml-gsd import issue

### ISSUE THREAD

**Issue by hunxjunedo** [mljs/global-spectral-deconvolution#124]
does the latest publish cause this ?  

`
  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/nmr-processing/nmr-processing.mjs:1:81897:
      1 │ ...t{addMissingShape as Mc}from"ml-gsd";import{getShape1D as jc}fro...
        ╵                                ~~~~~~~~

✘ [ERROR] Failed to resolve entry for package "ml-gsd". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46575:15)
    at resolvePackageEntry (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46572:3)
    at tryNodeResolve (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46388:16)
    at ResolveIdContext.resolveId (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46138:19)
    at PluginContainer.resolveId (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:48953:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66209:15
    at async file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46889:28
    at async requestCallbacks.on-resolve (/app/node_modules/esbuild/lib/main.js:1225:22)
    at async handleRequest (/app/node_modules/esbuild/lib/main.js:647:11)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46872:13)
    at handlePlugins (/app/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/app/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/app/node_modules/esbuild/lib/main.js:699:5)
    at /app/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/app/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/app/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:50862:33)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/ml-signal-processing/lib-esm/filters/x/calibrateX.js:1:20:
      1 │ import { gsd } from 'ml-gsd';
        ╵                     ~~~~~~~~`

**Comment by lpatiny** [comment]
I have introduced a bug during the migration to vitest that should be fixed now.

**Comment by hunxjunedo** [comment]
still not fixed 
![image](https://github.com/user-attachments/assets/f242adc2-5ca4-40c5-b8ad-6c64a2ee140d)
